version: "3.8"

services:
  go-server:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  react-frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    depends_on:
      - go-server
    environment:
      - SERVER_HOST=go-server
    ports:
      - "3000:3000"

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
